name: AtomicTags
main: DaRealAqua\SimpleTagsUI\Main
version: 1.0.0
api: 3.6.0
author: Based on DaRealAqua's SimpleTagsUI. Forked by YoYo.
commands:
  tags:
    description: Opens Tags Menu
    
permissions:
  tags.atomic:
    description: atomic Tag
    default: op
  tags.alien:
    description: alien Tag
    default: op
  tags.bombom:
    description: bombom Tag
    default: op
  tags.hacker:
    description: hacker Tag
    default: op
  tags.uwu:
    description: UwU Tag
    default: op
  tags.dragon:
    description: dragon Tag
    default: op
  tags.propvp:
    description: pro Tag
    default: op
  
